<!doctype html>
<meta charset="UTF-8">
<title>PHP Rise Framework</title>
<style>
* {
	box-sizing: border-box;
}
body, p, ol, ul, h1, h2, h3, h4, h5, h6 {
	padding: 0;
	margin: 0;
}
h1, h2, h3, h4, h5, h6 {
	font-size: 100%;
	font-weight: normal;
}
a {
	color: inherit;
}
main {
	width: 100%;
	position: absolute;
	top: 50%;
	margin-top: -120px;
	text-align: center;
}
.title {
	font: 100px sans-serif;
}
</style>
<?=$body?>
